# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

permissions:
  contents: read # Solo necesita leer el contenido del repositorio

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # Para macos y windows, r-build-args es una cadena vacía
          - {os: macos-latest,   r: 'release', r-build-args: ''}
          - {os: windows-latest, r: 'release', r-build-args: ''}
          # Para ubuntu, usamos los argumentos para compactar viñetas
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release', r-build-args: '--no-manual --compact-vignettes=gs+qpdf'}
          - {os: ubuntu-latest,   r: 'release', http-user-agent: 'release', r-build-args: '--no-manual --compact-vignettes=gs+qpdf'}
          - {os: ubuntu-latest,   r: 'oldrel-1', http-user-agent: 'release', r-build-args: '--no-manual --compact-vignettes=gs+qpdf'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          # Lógica condicional para `build_args`:
          # Si `r-build-args` NO está vacío, usa su valor.
          # Si `r-build-args` SÍ está vacío, lo pasa como 'character(0)' que R entiende como un vector vacío.
          build_args: ${{ matrix.config.r-build-args != '' && matrix.config.r-build-args || 'character(0)' }}
          # Puedes añadir --as-cran aquí si quieres que el check sea más estricto
